version: "3.8"

services:
  nginx:
    container_name: nginx
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"

  php:
    container_name: php
    build: images/php
    volumes:
      - ./lumen:/var/www/html
    working_dir: /var/www/html/
    command: php-fpm
    ports:
      - "9000:9000"